name: Build Mobile Apps (Android APK & iOS IPA)

on:
  workflow_dispatch:

env:
  NAME: "BuffCalendar"
  GODOT_VERSION: "4.3"

jobs:
  build-all:
    runs-on: macos-14
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pack Unsigned iOS IPA
        run: |
          mkdir -p ipa_out/Payload
          cp game.pck ipa_out/Payload/${{ env.NAME }}.pck
          cd ipa_out
          zip -r ../${{ env.NAME }}.ipa Payload

      - name: Download Android Template & Pack APK
        run: |
          # Скачиваем официальный пустой APK-скелет от разработчиков Godot
          curl -LO https://github.com{{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          unzip Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          
          # Зашиваем твой game.pck внутрь Андроида по правилам системы безопасности
          cp templates/android_release.apk ${{ env.NAME }}.apk
          zip -u ${{ env.NAME }}.apk game.pck

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}-iOS-IPA
          path: ${{ env.NAME }}.ipa

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}-Android-APK
          path: ${{ env.NAME }}.apk

